### ISSUE TITLE
Checker W2: Weight limits after leaving the suppliers

### ISSUE THREAD

**Issue by tomash1234** [renault-iaa/challenge-roadef-2022#23] opened 2022-09-04 10:49 UTC
Hi,
I think there is a problem in the checker when it checks W2 constrain after a truck leaves the first supplier. This happens only when the truck visits more than one supplier (in multiple datasets). It says the limit on the middle axle is exceeded while the truck is almost empty.

I think the problem might be in method `OutputTruck.calculateDistanceWeightOnAxles(int maxSupplierLoadingOrder)`, it calculates with `this.calculatedLoadedWeight` , which is not the weight of stacks with supplier order <= maxSupplierLoadingOrder, but the weight of all stacks.

Checker:
```
Constraint W2;the weight on middle axle of the trailer exceeds max weight;truck id = P195402703;recalculated weight on middle axle of the trailer = 20916,70;max weight on middle axle of the trailer = 12000,00;with suppliers = [0011635500]
```

My solution for P195402703 [Dataset: CA]:

```
supplier_code: 0011635500
------------------------------------
Stack P195402703_1, supp: 0011635500, x: 0-1206, weight: 168.95 kg
 > Item: 555G39804R, 168.95 kg
Stack P195402703_2, supp: 0011635500, x: 1206-2412, weight: 168.95 kg
 > Item: 555G29068R, 168.95 kg
em_m: 4421.315343105471, em_r: 5031.089698558322

supplier_code: 0061190700
-----------------------------------
...
...
em_m: 6294.9139464233995, em_r: 18336.469250327653
.```

**Comment by renault-iaa** [comment] 2022-09-08 15:38
Hello,

You are right : the problem is now solved in the last version committed v1.6.0. Thanks for the analysis.

**Closed as completed** 2022-09-12 08:08 UTC
