### ISSUE TITLE
Checker S5: Max weight above the bottom item of the stack

### ISSUE THREAD

**Issue by tomash1234** [renault-iaa/challenge-roadef-2022#21] opened 2022-09-02 10:11 UTC
Hi,
I am not sure how the constrain S5 exactly works. Is there for each pair (truck, product code) some maximal weight above the bottom item?
- Challenge document: `TMMtγ : maximal total weight of all the items packed above the bottom item associated with product γ in
any stack of truck t`
- Or it is defined for supplier / plant?  - from here: https://github.com/renault-iaa/challenge-roadef-2022/issues/4

Dataset [CI]
Trucks input file:
[Product code]    - [Truck Id]      -       [Max weight on the bottom item in stacks]
- 365300677R   -     P194414301	-  750
- 112205FD0B  -  P194414301	-  100000
- 112205FF1A -  P194414301	  - 100000
- 112204BB0A -	P194414301	- 100000
- 112205FA0A -	P194414301	- 100000
-  many more ...

I created stack for  P194414301
- 0090016800_03072022000991   	112205FF1A  <--- bottom item
- 0090016800_03072022001860	112204BB0A
- 0090016800_03072022001906	112205FA0A

And the checker says: 
`the weigth of the items above the bottom item of the stack exceeds the maximal weight           stack id = P194414301_1         weight of the items above the bottom item = 756,70           maximal weight authorized = 750`

**Comment by renault-iaa** [comment] 2022-09-05 12:29
Hello,

The maximal weight above the bottom item is associated with a pair  (truck, product code). There is a mistake in the checker, the stack you built is correct. I will make the correction in the next release of the checker.

**Comment by renault-iaa** [comment] 2022-09-08 15:37
Hello,

The problem is now solved in the last version committed v1.6.0.

**Comment by tomash1234** [comment] 2022-09-08 17:09
Thank you, it is working well now.

**Closed as completed** 2022-09-12 08:08 UTC
