### ISSUE TITLE
Checker -> Several trucks of the same type

### ISSUE THREAD

**Issue by gfpantoja** [renault-iaa/challenge-roadef-2022#20] opened 2022-09-01 14:22 UTC
Hello dear organizers. I am having a hard time with the checker when I use several trucks of the same type. Let's consider the case that I only use a truck type whose id is P123456 and that I need to use 3 trucks in total of this type (1 planned and 2 extra). My question is, which are the "Id Truck"s for each truck that I have to put in the output files? 

I am asking this because according to the rules, the first truck should be named P123456, the second one Q123456_2 and (I suppose that) the third one should be Q123456_3. When I run the checker with these ID Trucks, the checker crashes, and the report file is not generated (then I cannot know which constraints I am violating). But, if I use the Id trucks: P123456, P123456_2, and P123456_3, the report is generated, but it says that the Id Trucks P123456_2 and P123456_3 are unknown. 

Or maybe, is it possible for you to publish a solution for the dummy example (within the checker) that uses 2 trucks of the same type?

**Comment by tomash1234** [comment] 2022-09-01 19:07
Hi, I think I have a similar problem, the checker is crashing for some of my solutions. But I don't think it is caused by extra truck ids. I believe it is the correct way as you described, P123456, Q123456_2, Q123456_3, ... because I have some solutions with extra trucks and the checker works fine...  I think there is some other problem. Does your checker stacktrace look like this? 

java.util.IllegalFormatConversionException: f != java.lang.Integer
        at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source)
        at java.util.Formatter$FormatSpecifier.printFloat(Unknown Source)
        at java.util.Formatter$FormatSpecifier.print(Unknown Source)
        at java.util.Formatter.format(Unknown Source)
        at java.util.Formatter.format(Unknown Source)
        at java.lang.String.format(Unknown Source)
        at model.Checker.checkConstraintW1(Checker.java:664)
        at model.Checker.checkAllConstraints(Checker.java:88)
        at main.Main.main(Main.java:81)
2022-09-01 20:55:15.904 [main    ] ERROR - java.util.Formatter$FormatSpecifier.failConversion(Unknown Source)
2022-09-01 20:55:15.906 [main    ] ERROR - java.util.Formatter$FormatSpecifier.printFloat(Unknown Source)
2022-09-01 20:55:15.909 [main    ] ERROR - java.util.Formatter$FormatSpecifier.print(Unknown Source)
2022-09-01 20:55:15.909 [main    ] ERROR - java.util.Formatter.format(Unknown Source)
2022-09-01 20:55:15.910 [main    ] ERROR - java.util.Formatter.format(Unknown Source)
2022-09-01 20:55:15.910 [main    ] ERROR - java.lang.String.format(Unknown Source)
2022-09-01 20:55:15.912 [main    ] ERROR - model.Checker.checkConstraintW1(Checker.java:664)
2022-09-01 20:55:15.912 [main    ] ERROR - model.Checker.checkAllConstraints(Checker.java:88)
2022-09-01 20:55:15.913 [main    ] ERROR - main.Main.main(Main.java:81)

**Comment by gfpantoja** [comment] 2022-09-01 20:17
Hello, thanks for replying! Now I'm sure about the Id of the trucks :D
I don't know what I changed in my code, but the checker does not crash anymore.
I don't have the checker logs (I erased all checker-related files and downloaded them again), but since now I get a report file I suppose the logs were different. I hope you can find out what is causing the crash.

**Comment by renault-iaa** [comment] 2022-09-02 08:09
Hello @tomash1234,

Thanks for your post. The exception occurs in the generation of an anomaly message about the truck weight, the crash is incomprehensible. Can you send me the solution files which cause the crash ?

**Comment by tomash1234** [comment] 2022-09-02 08:34
Hi, I already found out why this happened to me. One of the trucks exceeded the max load weight limit. I already fixed it in my solver so I don't have the solutions files anymore.

**Comment by renault-iaa** [comment] 2022-09-02 13:39
Hello @tomash1234,

A new version of the checker has been committed, which corrects the crash.

**Closed as completed** 2022-09-05 08:42 UTC
